### ISSUE TITLE
feature request - --no-color option for ls

### ISSUE THREAD

**Issue by rhubarbdog** [dhylands/rshell#102]
i was using rshell from bash and typed `rshell --quiet ls /sd > file.txt` with the intention of using `file.txt` as input to a script. from bash when i type `cat file.txt` the ouput is coloured.

Can rshell detect it's stdout is being redirected to a file and automatically use `--no-color` or at least have it as an option to `ls` 
when i use linux `ls` with redirection it defaults to `--color=AUTO` which is no colour when redirecting, but sometimes i use `--color=ALWAYS`  then use `more` rather than `less` to view my data

**Comment by dhylands** [comment]
I just released 0.0.25 which includes this fix
