### ISSUE TITLE
NUCLEO-F446RE - timed out or error in transfer to remote

### ISSUE THREAD

**Issue by lukesky333** [dhylands/rshell#106]
Hi,

I'm trying to copy the uasyncio library to my NUCLEO-F446RE board (MB1136 C-03). I tried to copy the whole folder, I tried to copy single files -everytime I get the error message:

`timed out or error in transfer to remote`

Any idea what I can do?

**Comment by dhylands** [comment]
Please try rshell 0.0.26 

I just uplaoded a fix. Please let me know if it wrks for you.

**Comment by lukesky333** [comment]
Thanks a lot - it is fixed with rshell 0.0.26
