### ISSUE TITLE
Copy directories or all?

### ISSUE THREAD

**Issue by TravisJoe** [dhylands/rshell#21]
Hello, I was hoping that I could copy a folder, which has several modules, into my wipy and esp8266. But is appears the rshell cp command only covers single file transfer.

Is this already implemented and I just do not know it?
Is it possible?
Is it planned?

Just wondering the state of things. Otherwise this tools is amazing!

**Comment by dhylands** [comment]
rshell will soon be getting a working sync command which allows 2 directory trees to be synchronized.

@peterhinch is working on it.

**Comment by dhylands** [comment]
This was implemented in #23
