### ISSUE TITLE
REPL error on ESP32

### ISSUE THREAD

**Issue by AidanTek** [dhylands/rshell#51]
Hello - I've been through this process before without any issues, so I'm not sure what has gone wrong here, I'm guessing I have fudged installation somehow? Or forgotten a modifier?

I'm working on a project and set up a new Raspberry Pi for it with a clean install of Raspbian. I have only installed esptool.py, vim, screen and rshell. esptool.py does it's job and I can start an rshell session and copy files to the device, but I get an error when I try to open the REPL:

```
/home/pi> repl
Entering REPL. Use Control-X to exit.
Exception in thread REPL_serial_to_stdout:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/dist-packages/rshell/main.py", line 2244, in repl_serial_to_stdout
    save_timeout = dev.timeout()
TypeError: 'NoneType' object is not callable

```
I'm not sure what this is about at all! I'm using an ESP32 - I can use rshell and REPL with no problem on my Xubuntu laptop, and I can also use screen to access the REPL on the Pi - have I missed something here?

For the time being, I can copy files with rshell and access the REPL with screen - but I would rather not do it this way of course!

**Comment by mrichar1** [comment]
I'm also seeing this issue on esp8266 (Wemos D1 Mini) devices. It appears to be a bug introduced in `0.0.13` - rolling back to `0.0.12` (`pip install rshell==0.0.12`) and it works fine.

**Comment by dhylands** [comment]
This should now be fixed in https://github.com/dhylands/rshell/commit/190d5fc17b26e66a85a9943be40ffc820a1f37db

I've bumped the release to 0.0.14

Thanks for the report

**Comment by AidanTek** [comment]
Confirmed thanks!!
