### ISSUE TITLE
pyboard - False when copying files

### ISSUE THREAD

**Issue by diginfo** [dhylands/rshell#53]
I am encountering problems on all 3 of my MAC's whereby larger files (<20k) fail to upload.

I am using SD card so there's no problem with storage.

The file transfer starts, the green LED lights up, then a few seconds later it goes out and False is reported in the console.

After this, nothing further happens and I have to disconnect / reboot the pyboard.

I have tried playing with buffer size from 64 - 1024, tried enabling disabling ascii transfer mode, no difference.

I have also disabled usb storage mode to prevent that from interfering.

**Comment by diginfo** [comment]
I just upgraded to 0.14, now there is no 'false' message, however the transfer still fails.

**Comment by dhylands** [comment]
What board are you connecting to? For ESP8266/ESP32 I normally use buffer-size=32 and I also have to use the -a flag to force ASCII-only transfers.

**Comment by diginfo** [comment]
> pyboard - False when copying files

as per the title PYBOARD, yes I have already tried all of those options:

> I have tried playing with buffer size from 64 - 1024, tried enabling disabling ascii transfer mode, no difference.
