### ISSUE TITLE
Rsync not creating root folder

### ISSUE THREAD

**Issue by kevinkk525** [dhylands/rshell#70]
I tried to run this command:
`rshell rsync micropython_iot /pyboard/micropython_iot`
which fails because the folder "micropython_iot" does not exist on the device.
Coming from unix rsync I would expect it to create that folder for me.

**Comment by peterhinch** [comment]
Fair comment. I'll leave this open but it may be a while before I get time to look at it.

**Comment by dhylands** [comment]
This should be resolve in rshell 0.0.22

If you do rsync foo /flash/foo and /flash/foo doesn't exist then it will create it.
