### ISSUE TITLE
Feature Request - rsync

### ISSUE THREAD

**Issue by diginfo** [dhylands/rshell#80]
The rsync is very cool and works well, but it would be really nice to show some sort or progress in the console as you have no idea if it is hanged or what it has done.

Thanks

**Comment by dhylands** [comment]
If you do `help rsync` you'll see that it has a -v (or --verbose) option which should print some progress information.

**Comment by diginfo** [comment]
OOps - missed that, actually I would set this option every time, maybe verbose should be default :-)
