### ISSUE TITLE
RTC time not set when rsyncing

### ISSUE THREAD

**Issue by tuupola** [dhylands/rshell#82]
It seems that [setting the time](https://github.com/dhylands/rshell/blob/master/rshell/main.py#L934) with non pyboard boards always fails. This is because `rtc.datetime()` exists only in [pyb.RTC](http://docs.micropython.org/en/latest/library/pyb.RTC.html) while in [machine.RTC](https://docs.micropython.org/en/latest/library/machine.RTC.html) it is replaced with `rtc.init()`.

I noticed this while debugging why all my files are always uploaded when doing an rsync. I am using Loboris fork with an M5Stack.

**Comment by dhylands** [comment]
Thanks for the report. I'll look into it.

**Comment by dhylands** [comment]
This should be fixed in 0.0.20

The ESP8266 still uses rtc.datetime() so rshell has to try both

**Comment by tuupola** [comment]
Thanks! I am traveling for a week and unable to test on my board at the moment. Will test when I get back.
