### ISSUE TITLE
How to install RShell on Mac OS ?

### ISSUE THREAD

**Issue by mchobby** [dhylands/rshell#86]
Hi everyone, 
I would like to know how to install RShell on MacOS ? 
I have no Mac so your response and screenshoot would be welcome. Raison: book writing :-)
Regards,
Dominique

**Comment by dhylands** [comment]
rshell needs python3.

So you can do:
```
sudo python3 -m pip install rshell
```
to install it, and you can do:

```
sudo python3 -m pip install --upgrade rshell
```
to upgrade if a newer version becomes available.

I normally use `pip3` under linux (rather than `python3 -m pip`) but my Mac doesn't seem to have pip3 installed.

**Comment by mchobby** [comment]
Great! Thank :-)
