### ISSUE TITLE
Edit should abort updating the file when $EDITOR returns non-zero

### ISSUE THREAD

**Issue by kevinastone** [dhylands/rshell#94]
It's fairly customary that you can abort an edit session when the `$EDITOR` returns non-zero status code (`:cq` in vi as an example).

Can you check the return code on this line (https://github.com/dhylands/rshell/blob/master/rshell/main.py#L2223) and abort updating the file if this is non-zero?

**Comment by dhylands** [comment]
This should now be fixed in 0.0.24 0be291b27e8d34b834b25a48a397250fbc8e597f
